vazia = []
nomes = ["gabriel", "gustavo", "paulo","matheus"]
numeros =[100,44,88,99]
mista = ["gabriel", 82, "matheus", 1995, "joão", 44, "pedro", 182]
fusão = [nomes, numeros]
print(vazia)
print()
print(nomes)
print()
print(numeros)
print()
print(mista)
print()
print(fusão)
print()
print(min(numeros))
print()
print(max(numeros))
print()
print(sum(numeros))
print()
print(nomes[0],nomes[2])
print()
print(mista[4])
print()
print(fusão[0])
print()
print(fusão[1])
print()
print(fusão[0][1])
print()
print(fusão[0][0])
print()
print(fusão[0][1],fusão[1][0])
print("-="*30)
print()
print(nomes)
print()
nomes [3] = "maicon"
print(nomes)
print()
print(fusão)
print()
fusão [1][2] = 2004
print()
print(fusão)
print()
